### ISSUE TITLE
Cannot support default value before insert

### ISSUE THREAD

**Issue by ma349432587** [xylo/intellij-postfix-templates#132]
```
.test : test
    NON_VOID → $first$ + $first#1::"1st$"
```

**Comment by xylo** [comment]
You have a typo in your template.  The last $ is enclosed by quotes, so it's part of the default parameter.  And that's why your second variable is not closed by a $.

Moreover, if you repeat a variable that shall have a default value, then the default value has to be set for the first occurrence of the variable.  And if you have only one variable you can also skip the order attribute (`#1`).

So I guess you wanted to have something like this:?
```
.test : test
    NON_VOID → $first::"1st"$ + $first$
```
