### ISSUE TITLE
Templates cannot be reloaded with Control+S on Windows systems

### ISSUE THREAD

**Issue by 1bytee** [xylo/intellij-postfix-templates#17]
Under some circumstances, the file is being saved but the changes are not loaded. So another option in the `Tools` menu would be nice to reload from file manually.

**Comment by xylo** [comment]
Oh, I didn't have those problems yet.  Did you save the file via File -> Save all (Ctrl+S)?  Because the template reload is only triggered when you call the save function explicitly.  (Auto-save does not reload the templates).

**Comment by xylo** [comment]
OK, I just tested the plugin on a Windows machine and I had exactly the same problem.  The templates where never reloaded.  Since it works perfectly on Linux I'm a bit surprised.

However, I will try to fix it so that Ctrl+S works on Windows as well.  If that's not possible I will probably add a menu entry in the *Custom Postfix Templates* menu and set a shortcut for it.

Thanks for reporting the bug.
