### ISSUE TITLE
Please add support IDEA 2024.2 Thanks. 

### ISSUE THREAD

**Issue by suhengli** [xylo/intellij-postfix-templates#245]

**Comment by xylo** [comment]
Support for IDEA 2024.2 has been added.
Sorry for the delay.  Jetbrains made some big changes in gradle-intellij plugin and somehow the access to the EAP releases of IDEA via gradle is broken now or at least much more complicated.  I'll try to find a solution for this so that Custom Postfix Templates will be available for IDEA 2024.3 EAP releases (hopefully).
