### ISSUE TITLE
Replacing parts of expressions

### ISSUE THREAD

**Issue by rasfra** [xylo/intellij-postfix-templates#31]
Is this possible?
`String s = someString.nn -> String s = requireNonNull(someString)`

The only usable variable I find is $expr$ but this replaces whole expression leaving only `requireNonNull(someString)`

**Comment by xylo** [comment]
Well, in your case `someString` should be detected as expression to replace (`$expr$`) so that `String s = ` stays unchanged.  Unfortunately the current implementation of the postfix templates always take the whole string before the template name into account.  This is the same for most of the predefined IDEA postfix templates, such as `.if` or `.nn`.  However, IDEA has also some postfix templates that work differently, for instance `.var`.  And some of them ask you on which part of the expression the template shall be applied to.  Thus there could be options for this in future, but at the moment there is no such solution.  Personally, when I write code, I always start with the value, i.e. I write

`someString.nn`

and expand it to

`requireNonNull(someString)`

and then I add

`requireNonNull(someString).var`

and expand it to

`String s = requireNonNull(someString)`

This way it works also with the current plugin version.

**Comment by rasfra** [comment]
Thanks for the reply!

My use case is often modifying generated constructors to add notnull constraints on them, thus starting with an expression already. Maybe a normal live template is better to use for that - I'm just trying to get around the slightly longer process of selecting the variable and using shift alt j.

There are several official postfix completions utilizing this without asking about the context though, .not probably being the simplest one:  `m(b.not);` -> `m(!b);` so it sounds like it should be very possible as long as IDEA doesn't have special rules their own!

**Comment by xylo** [comment]
Yes, `.not` is another example for this.  It behaves similar to `.var`.  If you have an expression

`true && false.not`

it also asks you if you want to apply the template just to `false` or to `true && false`.  I would like to the the same functionality for my custom postfix templates.  I have to look into the code of `.not` to see how they solved it.

**Comment by xylo** [comment]
So it's on my TODO, especially since I want to be able to apply postfix templates to method parameters like in your example.

**Comment by rasfra** [comment]
Great, can't wait!

**Comment by xylo** [comment]
Implemented in version 1.0.2.
