### ISSUE TITLE
Is it possible to create template with all expressions with current offset?

### ISSUE THREAD

**Issue by m-titov** [xylo/intellij-postfix-templates#42]
Hi,
Is it possible?:
`someObj.someMethod().when -> when(someObj.someMethod())`

**Comment by xylo** [comment]
Yeah. Actually, it should work as you expected it, but it doesn't. Have to fix it.

**Comment by xylo** [comment]
OK, it's fixed in the next release (1.2.2).  At least the bug that not the full expression `someObj.someMethod()` got replaced.

There is still the problem that in Kotlin and JavaScript code the postfix template cannot offer you a choice between multiple expressions, e.g. when you have a line
```
1 + someObj.someMethod().when
```
you might want to replace `someObj.someMethod()` or `1 + someObj.someMethod()`.

In this case the template will not give you the choice but will replace the shorter term.

I don't know yet why this works with Java, but not with Kotlin or JavaScript.

**Comment by xylo** [comment]
Released version 1.2.2.

**Comment by m-titov** [comment]
Wow. Cool. Thanks a lot.
