### ISSUE TITLE
Wrong format and  postfix in JavaScript and typescript

### ISSUE THREAD

**Issue by aristotll** [xylo/intellij-postfix-templates#52]
I write a template in JavaScript(which also applies for typescript)

```
.forPost : for of in postfix templates
    ANY  →  ( let item of $expr$ ){ }
```
[].forPost

in `ts` file:

result:(note the trailing,which is wrong)
```
(let
item;
of [];
)
{
}
```

in `js` file (note the format )

```
(let
item
of []
)
{
}
```

**Comment by aristotll** [comment]
I try the same template in Java and it works.(type as any

**Comment by xylo** [comment]
Regarding the auto-reformatting: This is a general feature of IDEA.  Each code that gets inserted by a postfix template gets automatically reformatted according to the formatting rules of the specific language.  You can configure those formatting rules in the IDEA settings.

For instance, write "( let item of $expr$ ){ }" somewhere in your .js file and do a reformat in IDEA and you'll get the same result as above.

So the actual question is: "Why does IDEA reformat this code in this way?".
First of all, I'm absolutely not a JavaScript expert and therefore I might be wrong, but I've never seen a construction like "(let item of [])" and I have no idea what it shall do.  Are you sure this is valid JavaScript code?  IDEA also marks this code with the warning "Expression statement is not assignment or call", which means that this expression is actually doing nothing and can therefore be removed without harm.  So I guess that you forgot something in this statement.?

Regarding Java:
I also tried the template in Java and there it gets less reformatted, but this is only because the first round opening bracket already makes the code invalid regarding Java syntax and therefore the Java reformatter fails to reformat this code.

All live templates and postfix templates are generally made in a way that their application leads to a valid syntax tree again.  So for instance, if you want to create a for-loop-template you put in variables at the places that shall be filled in during the template expansion, but you cannot leave those places just empty.
Working example:
.forIn : for in
    ANY  →  for (var $var$ in $expr$) { $END$ }

Non-working example:
.forIn : for in
    ANY  →  for (var in $expr$) { $END$ }

**Comment by aristotll** [comment]
Thank you, I omitted the for in loop 😭(still don't why it is formated).
By the way,the syntax is `for let of`  https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of

**Comment by xylo** [comment]
Ah, OK, with `for` it makes sense.
