### ISSUE TITLE
Add support for CLion and Rust

### ISSUE THREAD

**Issue by thomaseizinger** [xylo/intellij-postfix-templates#62]
It would be great if this plugin would support other IDEs like Clion as well!

**Comment by xylo** [comment]
As far as I can tell Clion does not support Java, Scala, or Kotlin.  Thus, this add-on could be only used for JavaScript in Clion.  That's pretty little IMO and I doubt that a lot of people will use it for this tiny feature.

I think it's currently more important to support more programming languages, such as C or C++.  If those are supported by the plugin, adding support for Clion would also make sense.

However, because of my limited spare time I decided to implement and maintain only the languages that I use myself.  C and C++ are unfortunately not on my list.  Therefore, I hope that someone that uses C could join the project and add support for this language.

**Comment by thomaseizinger** [comment]
My main usecase would actually be for the `Rust` programming language. Maybe I should rephrase my issue :)

**Comment by xylo** [comment]
Untyped Rust support has been added in version 2.4.0.

**Comment by xylo** [comment]
And the plugin is already compatible with CLion.
